models:
  - name: dim_movies
    description: Dimension table for cleaned movie meta data
    columns:
     - name: movie_id
       description: Primary key
       tests:
        - not_null
     - name: movie_title
       description: Movies titles
       tests:
        - not_null
     - name: genre_array
       description: List of genres in array format
     - name: genres
       description: Raw genre string from sources
  - name: dim_users
    description: Dimension table for unique users from both ratings and 
    columns:
     - name: user_id
       description: Unique user identifier
       tests:
        - not_null
        - unique
   
  - name: dim_genome_tags
    description: Dimension table for genome tag labels
    columns:
     - name: tag_id
       description: Unique tag ID
       tests:
        - not_null
        # - unique
     - name: movie_title
       description: Movies titles
       tests:
        - not_null
     - name: genre_array
       description: List of genres in array format
     - name: genres
       description: Raw genre string from sources
  - name: fct_ratings
    description: Fact table of user ratings for movies
    columns:
     - name: user_id
       description: Foreign key to dim_users
       tests:
        - not_null
        - relationships: 
            to: ref('dim_movies')
            field: movie_id
     - name: rating
       description: User's rating for a movie
       tests:
        - not_null
     - name: rating_timestamp
       description: Unix timestamp when the rating was made
  - name: fct_genome_scores
    description: Fact table of relevance score per movie and tag
    columns:
     - name: movie_id
       description: Foreign key to dim_movies
       tests:
        - not_null
     - name: tag_id
       description: Foreign key to dim_genome_tags
       tests:
        - not_null
     - name: relevance_score
       description: Relevance score (0 to 1) for tags association
       tests:
        - not_null
     
     