version: 2

sources:
  - name: AmazonPrime
    schema: raw
    tables: 
     - name: r_movies
       identifier: raw_movies
     - name: r_ratings
       identifier: raw_ratings
     - name: r_tags
       identifier: raw_tags
     - name: r_genome_tags
       identifier: raw_genome_tags
     - name: r_genome_score
       identifier: raw_genome_score
     - name: r_link
       identifier: raw_links
